### ISSUE TITLE
click function not working 

### ISSUE THREAD

**Issue by rr1010** [giacomodeliberali/node-jquery#1]
I was trying to use the click function present in the jquery 3.3.1 but it doesnt work
.html
<!DOCTYPE html>
...
<button id="login">Login</button>
...

.js
$('#login').click(function (r) {
        console.log('Clicked login');
    });

**Comment by giacomodeliberali** [comment]
This "library" can not be used in a browser environment, because it does not interact with the window object you expect but rather with the one provided by [jsDom](https://github.com/jsdom/jsdom). Its main purpose is to use JQuery DOM manipulation to perform parsing of HTML pages on Node.
